server:
  port: ${port:8089}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL:} #jdbc:postgresql://localhost:5432/jewelry
    username: ${JDBC_DATABASE_USERNAME:} #postgres
    password: ${JDBC_DATABASE_PASSWORD:} #1234
    #driver-class-name: ${JDBC_DATABASE_DRIVER:}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    web:
      pageable:
        one-indexed-parameters: true
logging:
  level:
    root: warn
    org.springframework: debug
    '[springboot.jewelry.api]': debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
jewelry:
  app:
    jwt-secret: khongcochuoibimat
    jwt-duration: 900000 #900000 # 15 minutes
    jwt-refresh-duration: 604800000 #604800000 # 7 days
  gdrive:
    folder:
      product: 1fkgIXvbjQ4n20FArIiA5Nxb_3oukKcmk